### ISSUE TITLE
query

### ISSUE THREAD

**Issue by best2333** [naiarako/attomo#1]
Dear author Hello, I would like to ask why the ipynb file running, can not get the desired results, I choose the parameters are also mentioned in your paper parameters, I hope you can help me to answer my doubts, thank you very much
![1](https://github.com/naiarako/attomo/assets/127099481/2d9f3a56-7de7-4591-89da-f8e0e244f0d3)
![2](https://github.com/naiarako/attomo/assets/127099481/6b4d40d5-6578-4da4-8c5c-888ef7efd96a)
![3](https://github.com/naiarako/attomo/assets/127099481/a5aa395d-f1bf-
![4](https://github.com/naiarako/attomo/assets/127099481/00a84575-6887-4803-ad12-61c214adcfda)
443f-a902-353f4e9e2c6d)

**Comment by naiarako** [comment]
Thank you for testing the code. It seems that the acquisition setup of the calibration data does not match the one used for computing phantom data with k-Wave. I have updated the k-Wave script to fix this issue.
